# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [4]:
import pandas as pd 
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

In [5]:
cars1 = pd.read_csv('cars1.csv')
cars2 = pd.read_csv('cars2.csv')

   ### Step 3. Assign each to a variable called cars1 and cars2

In [6]:
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [7]:
cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [10]:
cars1.groupby(by = ['Unnamed: 9', 'Unnamed: 10','Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']).count()

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model, origin, car]
Index: []

In [13]:
cars1 = cars1.drop(columns=['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'],errors='ignore')
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [29]:
print(cars1.shape[0],' ',cars2.shape[0])
cars1.query("car =='ford pinto' ")

198   200

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
32,25.0,4,98,?,2046,19.0,71,1,ford pinto
112,19.0,4,122,85,2310,18.5,73,1,ford pinto
130,26.0,4,122,80,2451,16.5,74,1,ford pinto
168,23.0,4,140,83,2639,17.0,75,1,ford pinto
174,18.0,6,171,97,2984,14.5,75,1,ford pinto

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [28]:
car = pd.concat([cars1,cars2]).reset_index()
car.groupby(by = ['car','model']).count().query('mpg >1')

,,index,mpg,cylinders,displacement,horsepower,weight,acceleration,origin
car,model,,,,,,,,
ford pinto,75,2,2,2,2,2,2,2,2
plymouth reliant,81,2,2,2,2,2,2,2,2

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [43]:
rng = np.random.default_rng(12345)
car['owner'] = rng.integers(low=15000, high=73000,size = car.shape[0])
car

,index,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owner
0,0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,55554
1,1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,28185
2,2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,60741
3,3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,33371
4,4,17.0,8,302,140,3449,10.5,70,1,ford torino,26842
...,...,...,...,...,...,...,...,...,...,...,...
393,195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,23300
394,196,44.0,4,97,52,2130,24.6,82,2,vw pickup,44418
395,197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,39519
396,198,28.0,4,120,79,2625,18.6,82,1,ford ranger,17230
397,199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,59335

### Step 8. Add the column owners to cars