# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd 
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [ ]:
np.random.seed(101)
rd_1 = np.random.randint(low = 1, high = 4, size = 100)
rd_2 = np.random.randint(low = 1, high = 3, size = 100)
rd_3 = np.random.randint(low = 10000, high = 30000, size = 100) 
d

### Step 3. Let's create a DataFrame by joinning the Series by column

In [35]:
data_0 = pd.DataFrame({
    'c1': rd_1,
    'c2': rd_2,
    'c3': rd_3
}
)
data_0.head()

   c1  c2     c3
0   2   1  16801
1   3   2  26130
2   2   1  24146
3   2   2  20328
4   2   1  10591

In [46]:
data_0 = pd.DataFrame([rd_1,rd_2,rd_3]).T
data_0.columns = ['C1','C2','C3']
data_0.head()

   C1  C2     C3
0   2   1  16801
1   3   2  26130
2   2   1  24146
3   2   2  20328
4   2   1  10591

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [47]:
data_0.columns = ['beds','bathrs','price_sqr_meter']

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [54]:
big_column = pd.DataFrame(
    {
    'big_column':pd.concat([pd.Series(rd_1),pd.Series(rd_2),pd.Series(rd_3)])
    }
).reset_index()

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [55]:
big_column

     index  big_column
0        0           2
1        1           3
2        2           2
3        3           2
4        4           2
..     ...         ...
295     95       28928
296     96       27685
297     97       20638
298     98       12160
299     99       18084

[300 rows x 2 columns]

### Step 7. Reindex the DataFrame so it goes from 0 to 299