# Iris

### Introduction:

This exercise may seem a little bit strange, but keep doing it.

### Step 1. Import the necessary libraries

In [9]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).

In [8]:
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',header=None)
iris.columns = ['sepal_length','sepal_width','petal_length','petal_width','class']
iris

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

### Step 3. Assign it to a variable called iris

In [ ]:

conditions = [
    (iris['sepal_length']>=6.7) & (iris['sepal_width']>=3.5) & (iris['petal_length']>=5.1),
    (iris['sepal_length']>=6.7) & (iris['sepal_width']>=3.5),
    (iris['sepal_length']>=6.7)
]

choices = [
    'big',
    'biger',
    'bigest'
]

iris['size'] = np.select(
    conditions,
    choices,
    default='small'
)

iris['size'].value_counts()

size
small     122
bigest     25
big         3
Name: count, dtype: int64

In [22]:
g = iris.groupby('class')['sepal_width']

iris.groupby('class').agg(
    mean = ('sepal_width',pd.Series.mean)
)

                  mean
class
Iris-setosa      3.418
Iris-versicolor  2.770
Iris-virginica   2.974

In [ ]:
g.apply(lambda x:())

class
Iris-setosa        0.381024
Iris-versicolor    0.313798
Iris-virginica     0.322497
Name: sepal_width, dtype: float64

### Step 4. Create columns for the dataset

In [57]:
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class

### Step 5.  Is there any missing value in the dataframe?

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

### Step 7. Good, now lets substitute the NaN values to 1.0

### Step 8. Now let's delete the column class

### Step 9.  Set the first 3 rows as NaN

### Step 10.  Delete the rows that have NaN

### Step 11. Reset the index so it begins with 0 again

### BONUS: Create your own question and answer it.