# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd 
import numpy as mp

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

In [2]:
baby_names = pd.read_csv("US_Baby_Names_right.csv")

### Step 3. Assign it to a variable called baby_names.

In [4]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 4. See the first 10 entries

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [6]:
baby_names = baby_names.drop(columns=['Unnamed: 0','Id'])

### Step 6. What year has the highest number of baby names in the dataset?

In [21]:
baby_names_agg = baby_names.groupby(by = 'Year').count()['Name'].reset_index().sort_values(by = 'Name')
baby_names_agg

    Year   Name
0   2004  86420
1   2005  88494
2   2006  91803
7   2011  92545
9   2013  92743
8   2012  93024
6   2010  93307
10  2014  94148
3   2007  94332
5   2009  94609
4   2008  94970

In [24]:
baby_names_agg.loc[baby_names_agg['Name'].idxmax(),'Year']

np.int64(2008)

### Step 7. Is there more male or female names in the dataset?

In [43]:
def is_male(x):
    return (x == 'M').sum()

def is_female(x):
    return (x == 'F').sum()


baby_names.groupby(lambda x: 'Total').agg(
    Male = ('Gender',is_male),
    Female = ('Gender',is_female),
)

         Male  Female
Total  457549  558846

In [27]:
(baby_names.Gender == 'M').sum()

np.int64(457549)

### Step 8. Group the dataset by name and assign to names

In [47]:
names = baby_names.groupby(by = 'Name').agg(
    Count = ('Count',pd.Series.sum)
).reset_index().sort_values(by = 'Count',ascending=False)

names

           Name   Count
7198      Jacob  242874
5378       Emma  214852
12111   Michael  214405
5579      Ethan  209277
6973   Isabella  204798
...         ...     ...
162    Abigaile       5
15003    Shatha       5
17605  Zykeriah       5
17578   Zunaira       5
5703       Ezel       5

[17632 rows x 2 columns]

### Step 9. How many different names exist in the dataset?

In [48]:
names['Name'].nunique()

17632

### Step 10. What is the name with most occurrences?

In [50]:
names.loc[names['Count'].idxmax()]

Name      Jacob
Count    242874
Name: 7198, dtype: object

### Step 11. How many different names have the least occurrences?

In [52]:
names.loc[names['Count'] ==5]

           Name  Count
17616    Zymari      5
17608  Zykierra      5
4719      Dhyan      5
4718     Dhwani      5
8348     Jleigh      5
...         ...    ...
162    Abigaile      5
15003    Shatha      5
17605  Zykeriah      5
17578   Zunaira      5
5703       Ezel      5

[2578 rows x 2 columns]

### Step 12. What is the median name occurrence?

In [53]:
names['Count'].median()

np.float64(49.0)

### Step 13. What is the standard deviation of names?

In [54]:
names['Count'].std()

np.float64(11006.06946789057)

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [55]:
names['Count'].describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64